[package]
name = "StakedLPTOracle"
version = "1.1.0"

[addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
[dependencies.FixedPoint64]
git = "https://github.com/ThalaLabs/fixed_point64.git"
rev = "mainnet"